language: java
jdk:
  - oraclejdk8
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test
after_success:
  - mvn --non-recursive jacoco:merge coveralls:report
